name: stactools-canelevation
channels:
  - conda-forge
  - defaults
dependencies:
  - conda-forge::gdal 
  - conda-forge::pdal
  - conda-forge::python-pdal
  - conda-forge::geos
  - conda-forge::rasterio
